apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc-master
  hostPath:
    path: /mnt/data/postgres-master