apiVersion: v1
kind: Service
metadata:
  name: postgres-1
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: postgres-1
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432