apiVersion: v1
kind: Pod
metadata:
  name: test-command
  labels:
    name: test-command
spec:
  containers:
  - name: test-command
    image: bitnami/kubectl:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 1111
