apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-delete-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-delete-test
  template:
    metadata:
      labels:
        app: postgres-delete-test
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-delete-test
