apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-delete-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc-delete-test
  hostPath:
    path: /mnt/data/postgres-delete-test
