datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        url: 10.244.1.156:5432
        database: mydatabase
        user: postgres
        secureJsonData:
          password: mysecretpassword
        jsonData:
          sslmode: "disable"
          postgresVersion: 1300
