apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-3
  template:
    metadata:
      labels:
        app: postgres-3
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5433
      #     volumeMounts:
      #       - name: postgres-data
      #         mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: postgres-data
      #     persistentVolumeClaim:
      #       claimName: postgres-pvc-2