apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  selector:
    app: postgres-master
  ports:
    - name: postgres-master
      port: 5432
      targetPort: 5432
  type: LoadBalancer