apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test-write
  template:
    metadata:
      labels:
        app: postgres-test-write
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432