apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-1
  template:
    metadata:
      labels:
        app: postgres-1
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-2
  template:
    metadata:
      labels:
        app: postgres-2
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5433
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-2
