apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc-1
  hostPath:
    path: /mnt/data/postgres-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc-2
  hostPath:
    path: /mnt/data/postgres-2
