apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-sc-1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-sc-2