apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc-test
  hostPath:
    path: /mnt/data/postgres-test
