apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-sc-test
