apiVersion: v1
kind: Secret
metadata:
  namespace: metallb-system
  name: memberlist
data:
  secretkey: "WgSqnUNq47gzWGwzihWqZ5qLxx0bVu/QVqJdr5iQWhKH+Cnz4sBD/vdSL6ZwXp/opFhRDYdXYypreJykP0ov9xOdmhciH7MAZHWMqUmTIGP40aHPEAKMFTOfkhZVMdc6QqriNvXgYZfmgXmOKVSbJjwkXo1OOCwE0kaoCwLDeyo="
