---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pgupgrade.zzh.domain
  resources:
  - pgupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgupgrade.zzh.domain
  resources:
  - pgupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - pgupgrade.zzh.domain
  resources:
  - pgupgrades/status
  verbs:
  - get
  - patch
  - update
