# permissions for end users to edit webservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webserver-operator
    app.kubernetes.io/part-of: webserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - webservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - webservers/status
  verbs:
  - get
